@echo off

if %PROCESSOR_ARCHITECTURE%==AMD64 (
	set CSDTKMAKEDIR=make64
) else (
	set CSDTKMAKEDIR=make
)

set CSDTKVER=4
set CSDTKVERSION=4.2
set CSDTK4INSTALLDIR=%~dp0
set PATH=%CSDTK4INSTALLDIR%%CSDTKMAKEDIR%;%CSDTK4INSTALLDIR%perl\bin;%CSDTK4INSTALLDIR%python27;%CSDTK4INSTALLDIR%mips-elf-4.4.2\bin;%CSDTK4INSTALLDIR%mips-rda-elf-7.1.0\bin;%CSDTK4INSTALLDIR%rv32-elf-5.4.1\bin;%CSDTK4INSTALLDIR%nanopb-0.3.9;%CSDTK4INSTALLDIR%mingw32\bin;%PATH%

